dist: bionic

install:
  - sudo apt update
  - sudo apt install graphviz

script:
  - make

after_script:
  # The file should be created
  - if [[ ! -f "my.pdf" ]]; then echo "File 'my.pdf' not created "; exit 1; fi
  # After a make, all should be done
  - if [ "$(make)" != "make: Nothing to be done for 'all'." ]; then echo "second make should do nothing"; exit 1; fi

